FROM alpine:3.23

RUN apk add --no-cache \
    build-base cmake git curl wget jq tar gzip unzip \
    openssh-client ca-certificates \
    python3 py3-pip py3-setuptools py3-wheel py3-virtualenv \
    nodejs npm \
    go \
    rust cargo \
 && mkdir -p /workspace

WORKDIR /workspace
